### PR TITLE
add team usergroups

### PR DESCRIPTION
**Pull request by opticaldrive**
Added Pings for When a team wins, the teams get pinged

People can add and remove  themselvess from  the group, preventing unwanted pings.

### CODE REVIEW

**Comment by opticaldrive** [comment]
Not sure if I did it right.......
Thank you!

**Comment by opticaldrive** [comment]
What do you think of this?
I added the ping groups....

**Comment by mrhappyma** [comment]
- [denopolled](https://hackclub.slack.com/archives/C0610PL4VSQ/p1701397836180409) in slack, I don't think most people want pings.
- For stuff like this with IDs I'd like to use environment variables, so they work with testing in a different workspace. I'll update your fork with that ~~+ resolve conflicts caused by b5073c996c38d422c72d30e00de2468357b2b497~~
- I really like the idea of adding team members to groups (secret team channels?)! we can probably automate that too

**Comment by opticaldrive** [comment]
Seems good!
Has the feature been removed?
What are environmental variables(maybe continue in slack?)?
I guess I will try and add emoji decorating to the leaderboard and stuff.

**Comment by mrhappyma** [comment]
- environment variables (env sometimes) are a variable system in the shell/terminal, which can be accessed in the code and used to store values we don't want to hard-code, stuff like the token or IDs that will change by deployment
- the pr currently has the same effect, but the group IDs are stored in environment vars
- I expect we will have it not ping (I believe you can mention groups but not have it notify them?) and add members to groups when the team is assigned. I'll look more into this this afternoon.
- sounds good, please make sure to do that on a different branch

**Comment by opticaldrive** [comment]
Will try.....
I will look into env

**Comment by mrhappyma** [comment]
looks like you can't mention groups without notifying them

**Comment by opticaldrive** [comment]
That's too bad.....
Wait, you approved it?

**Comment by opticaldrive** [comment]
I will try to add env things......

**Comment by mrhappyma** [comment]
I replaced it with just adding to the usergroups. What are you adding to the env?

**Comment by opticaldrive** [comment]
Nothing yet.
I have not started on it.

**Pull request merged**
