### PR TITLE
Feature - (temp) bans WIP

### PR DESCRIPTION
**Pull request by jakjakob**
basically a first draft to simply ban people, temp ban them etc. without needing an admin to kick them from a channel, including ban reason, moderator that banned etc.;

### To-do list

- [ ] automatically unban people
- [ ] send message on unban
- [ ] ban history
- [ ] warn system
- [ ] add warns and ban logs to the canvas
- [ ] idk what else

### CODE REVIEW

**Comment by opticaldrive** [comment]
Interesting work.
One possible feature:
Open source the log by editing canvass

**Comment by jakjakob** [comment]
it is still kinda basic since I am learning the stuff that is happening there rn but anyway - I'll add that to the todo

**Comment by jakjakob** [comment]
On a Quick Look I am not finding documentation on the proposed canvas feature, do you have any resources @V205Arduino ?

**Comment by mrhappyma** [comment]
sounds like a good plan. please make sure you're caching bans, not making a database call on every message.

**Comment by opticaldrive** [comment]
https://api.slack.com/reference/functions/canvas_update_content
Would likely have helpful content.

**Comment by jakjakob** [comment]
Due to https://github.com/mrhappyma/slack-ups-and-downs/issues/7 I will close this and re-open a new one WIP one on the new repo

**Comment by jakjakob** [comment]
for reference https://github.com/mrhappyma/ups-and-downs-rtm/pull/2

**Pull request closed without merging**
